<table class="form-list" cellspacing="0">
  <tbody>
    <tr>
      <td class="label"><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></td>
      <td class="value"><img src="<?php echo $this->getSkinUrl('eloom/yapay/images/logo.png'); ?>"/></td>
    </tr>
    <?php if ($_specificInfo = $this->getSpecificInformation()): ?>
      <?php foreach ($_specificInfo as $_label => $_value): ?>
        <tr>
          <td class="label"><?php echo $this->escapeHtml($_label) ?></td>
          <td class="value"><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n")) ?></td>
        </tr>
      <?php endforeach; ?>
    <?php endif; ?>

    <?php $link = $this->getBilletLink(); ?>

    <?php if ($this->getInfo()->getLastTransId() && $link): ?>
      <tr>
        <td class="label"></td>
        <td class="value">
          <a href="<?php echo $link; ?>" target="blank" class="hollow button secondary" title="<?php echo Mage::helper('checkout')->__('Print Boleto'); ?>">
            <i class="fa fa-barcode" aria-hidden="true"></i>
            <?php echo Mage::helper('checkout')->__('Print Boleto'); ?>
          </a>
        </td>
      </tr>
    <?php endif; ?>
  </tbody>
</table>
<?php echo $this->getChildHtml(); ?>