<script type="text/javascript">
	function yapayLogger() {
		new Ajax.Request("<?php echo $this->getLoggerUrl() ?>", {
			method: 'get',
			onSuccess: function (transport) {
				if (transport.responseText) {
					document.getElementById('yapay_log_result').value = transport.responseText;
				    document.getElementById('yapay_log_result').style.display = 'block';
				}
			}
		});
	}
</script>

<?php echo $this->getButtonHtml() ?>