<?php $code = 'terminal_cc'; ?>
<ul id="payment_form_<?php echo $code ?>" class="form-list" style="display: none;">
  <li class="yapay-cc-number">
    <label><?php echo $this->__('CC Number') ?></label>
    <input type="tel" name="payment[yapay_cc_number]" id="<?php echo $code ?>-yapay-cc-number" class="input-text required-entry validate-cc-number-eloom yapay-cc-number" autocomplete="off"/>
  </li>
  <li class="yapay-cc-owner">
    <label><?php echo $this->__('CC Owner') ?></label>
    <input type="text" name="payment[yapay_cc_owner]" id="<?php echo $code ?>-yapay-cc-owner" class="input-text required-entry validate-cc-owner-eloom yapay-cc-owner" style="text-transform: uppercase;" autocomplete="off"/>
  </li>
  <li class="yapay-cc-expiry">
    <label><?php echo $this->__('CC Expiry') ?><span><?php echo $this->__('Mês/Ano') ?></span></label>
    <input type="tel" name="payment[yapay_cc_expiry]" id="<?php echo $code ?>-yapay-cc-expiry" class="input-text required-entry" placeholder="MM/AAAA" autocomplete="off"/>
  </li>
  <li class="yapay-cc-cvc">
    <label><?php echo $this->__('CC CVC') ?></label>
    <input type="tel" name="payment[yapay_cc_cvc]" id="<?php echo $code ?>-yapay-cc-cvc" class="input-text required-entry validate-cc-cvn" autocomplete="off"/>
  </li>
  <li>
    <label><?php echo $this->__('Installments') ?></label>
    <select name="payment[yapay_cc_installments]" id="<?php echo $code ?>-installments" class="input-text required-entry">
      <option value=""><?php echo $this->__('Informe o número do cartão') ?></option>
    </select>
  </li>
  <li>
    <input type="checkbox" name="payment[yapay_cc_holder_another]" id="<?php echo $code ?>-yapay-cc-holder-another" value="1" />
    <label for="<?php echo $code ?>-yapay-cc-holder-another" class="holder-another"><?php echo $this->__('Holder Another') ?></label>
  </li>
  <li class="yapay-cc-holder yapay-cc-holder-cpf">
    <label><?php echo $this->__('Holder CPF') ?></label>
    <input type="tel" name="payment[yapay_cc_holder_cpf]" id="<?php echo $code ?>-yapay-cc-holder-cpf" class="input-text idecheckoutvm-cpf" autocomplete="off" />
  </li>
  <li class="yapay-cc-holder yapay-cc-holder-phone">
    <label><?php echo $this->__('Holder Phone') ?></label>
    <input type="tel" name="payment[yapay_cc_holder_phone]" id="<?php echo $code ?>-yapay-cc-holder-phone" class="input-text" autocomplete="off"/>
  </li>
  <li class="yapay-cc-holder yapay-cc-holder-birth-date">
    <label><?php echo $this->__('Holder Birth Date') ?></label>
    <input type="tel" name="payment[yapay_cc_holder_birth_date]" id="<?php echo $code ?>-yapay-cc-holder-birth-date" placeholder="DD/MM/AAAA" class="input-text" autocomplete="off"/>
  </li>
  <li>
    <input type="hidden" name="payment[yapay_cc_type]" id="<?php echo $code ?>-yapay-cc-type" />
	  <input type="hidden" name="payment[yapay_cc_finger_print]" id="<?php echo $code ?>-yapay-finger-print" />
  </li>

  <li>
      <div class="buttons-set">
          <button type="button" class="button" onclick="payment.save(this)"><span><span><?php echo $this->__('Process Payment') ?></span></span></button>
        <span id="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Processing...') ?>" title="<?php echo $this->__('Processing...') ?>" class="v-middle" /> <?php echo $this->__('Processing...') ?>
        </span>
      </div>
  </li>
</ul>

<script type="text/javascript">
//<![CDATA[
  Eloom.Yapay.Terminal.PaymentCc.config = {code: "<?php echo $code ?>",
    amount: <?php echo $this->getGrandTotal(); ?>,
    firstInstallmentAmount: <?php echo $this->getFirstInstallmentAmount(); ?>,
    percentualDiscount: <?php echo $this->getPercentualDiscount(); ?>,
    minInstallment: <?php echo $this->getMinInstallment(); ?>,
    totalInstallmens: <?php echo $this->getTotalInstallments(); ?>
  };
  Eloom.Yapay.Terminal.PaymentCc.init();

    $('<?php echo $code ?>-yapay-cc-holder-cpf').observe('keyup', function () {
        ideMaskInst.inject(this, ideMaskInst.cpf);
    }).triggerEvent('keyup');
    $('<?php echo $code ?>-yapay-cc-holder-phone').observe('keyup', function () {
        ideMaskInst.inject(this, ideMaskInst.phone);
    }).triggerEvent('keyup');
    $('<?php echo $code ?>-yapay-cc-holder-birth-date').observe('keyup', function () {
        ideMaskInst.inject(this, ideMaskInst.date);
    }).triggerEvent('keyup');
//]]>
</script>